basePath: /api/v1
definitions:
  crypto-price-service_internal_delivery_http_dto.ErrorBody:
    properties:
      cause:
        type: string
      code:
        type: integer
      detail:
        type: string
      message:
        type: string
    type: object
  crypto-price-service_internal_delivery_http_dto.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorBody'
    type: object
  internal_delivery_http_handlers_coin_addCoin.Request:
    properties:
      name:
        type: string
      symbol:
        type: string
    required:
    - name
    - symbol
    type: object
  internal_delivery_http_handlers_coin_addCoin.SuccessResponse:
    properties:
      createdAt:
        type: string
      name:
        type: string
      symbol:
        type: string
    type: object
  internal_delivery_http_handlers_coin_watchlist.Coin:
    properties:
      created_at:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      symbol:
        type: string
    type: object
  internal_delivery_http_handlers_coin_watchlist.SuccessResponse:
    properties:
      coins:
        items:
          $ref: '#/definitions/internal_delivery_http_handlers_coin_watchlist.Coin'
        type: array
    type: object
  internal_delivery_http_handlers_prices_AllForCoin.CoinPrice:
    properties:
      created_at:
        type: string
      price:
        type: number
    type: object
  internal_delivery_http_handlers_prices_AllForCoin.SuccessResponse:
    properties:
      prices:
        items:
          $ref: '#/definitions/internal_delivery_http_handlers_prices_AllForCoin.CoinPrice'
        type: array
    type: object
  internal_delivery_http_handlers_prices_closestToTimestamp.SuccessResponse:
    properties:
      created_at:
        type: string
      price:
        type: number
      symbol:
        type: string
    type: object
info:
  contact: {}
  description: API for watching crypto prices
  title: Crypto Price API
  version: "1.0"
paths:
  /coins:
    get:
      description: Returns a list of all coins currently in the watchlist with their
        details
      produces:
      - application/json
      responses:
        "200":
          description: List of coins in the watchlist
          schema:
            $ref: '#/definitions/internal_delivery_http_handlers_coin_watchlist.SuccessResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
      summary: Get list of watched coins
      tags:
      - Coins
    post:
      consumes:
      - application/json
      description: Adds a new coin to the watchlist and returns the created coin
      parameters:
      - description: Add coin request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_handlers_coin_addCoin.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created coin object
          schema:
            $ref: '#/definitions/internal_delivery_http_handlers_coin_addCoin.SuccessResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
      summary: Add a coin to the watchlist
      tags:
      - Coins
  /coins/{symbol}:
    delete:
      description: Removes a coin from the watchlist by its symbol
      parameters:
      - description: Coin symbol (e.g. BTC, ETH)
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Coin removed successfully (no content)
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
      summary: Remove coin from watchlist
      tags:
      - Coins
  /coins/{symbol}/price/closest:
    get:
      description: Returns the price record closest to the specified timestamp for
        a given coin symbol
      parameters:
      - description: Coin symbol (e.g. BTC, ETH)
        in: path
        name: symbol
        required: true
        type: string
      - description: Timestamp in milliseconds
        format: int64
        in: query
        name: timestamp
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_delivery_http_handlers_prices_closestToTimestamp.SuccessResponse'
        "400":
          description: Invalid timestamp or missing parameters
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
        "404":
          description: Coin not found or no price data exists
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
      summary: Get the closest price for a coin at a given timestamp
      tags:
      - Prices
  /coins/{symbol}/prices:
    get:
      consumes:
      - application/json
      description: Returns all recorded prices for the given coin symbol
      parameters:
      - description: Coin symbol (e.g. BTC, ETH)
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_delivery_http_handlers_prices_AllForCoin.SuccessResponse'
        "404":
          description: Coin does not exist
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/crypto-price-service_internal_delivery_http_dto.ErrorResponse'
      summary: Get all prices for a coin
      tags:
      - Prices
swagger: "2.0"
